language: python

sudo: false

python:
  - 2.7

before_install:
- git clone --depth=50 --branch=master https://github.com/keceli/QTC.git qtc
- cd qtc/
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install numpy psutil
- conda install -c openbabel openbabel
- conda install -c mcs07 cirpy

script:
- python obtools.py
