#conda env create -f environment.yml
#source activate qtc-env

name: qtc-env

channels:
    - pacchem
    - openbabel
    - conda-forge  # needed for libxrender, which openbabel is missing
    - mcs07

dependencies:
    - pip
    - python=2.7
    - psutil
    - pytest
    - mcs07::cirpy
    - openbabel::openbabel
    - conda-forge::xorg-libxrender
    - pacchem::x2z
    - pacchem::mess
    - pacchem::pac99
    - pacchem::thermp
    - pacchem::rcdriver
