name: qtc-env

channels:
    - openbabel
    - conda-forge  # needed for libxrender, which openbabel is missing
    - mcs07
    - pacchem

dependencies:
    - pip
    - python=2.7
    - xorg-libxrender
    - numpy
    - psutil
    - openbabel
    - cirpy
    - pytest
    - x2z
    - mess
