# cmd: conda build . --python 2 -c pacchem -c conda-forge -c openbabel -c mcs07
package:
    name: qtc
    version: 0.1.0

source:
    path: .

requirements:
    build:
        - pip
        - python
    run:
        - python
        - numpy
        - psutil
        - pytest
        - mcs07::cirpy
        - openbabel::openbabel
        - conda-forge::xorg-libxrender
        - pacchem::x2z
        - pacchem::mess
        - pacchem::pac99
        - pacchem::thermp
