version: 2
jobs:
    build-ubuntu:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout
            - run: 
                name: Create conda environment
                command: |
                    conda env create -f environment.yml  # create the qtc-env environment
            - run:
                name: Install QTC and run tests
                command: |
                    source activate qtc-env
                    pip install .               # uses the setup.py file
                    python -m pytest -v tests/  # finds and runs tests
workflows:
    version: 2
    build-all:
        jobs:
            - build-ubuntu
